version: '3.7'

services:

  # Mongo service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - my_net

  # Redis service
  redis:
    image: "redis:latest"
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    networks:
      - my_net

  # App service
  app:
    depends_on:
      - mongodb
      - redis
    container_name: "UM_App"
    environment:
      - WATCHPACK_POLLING=true
    restart: unless-stopped
    build:
      context: ./
      dockerfile: dockerfile
    expose:
      - 80
      - 2999
      - 3001
      - 3000
      - 3010
      - 9230
      - 9231
      - 9232
    ports:
      - "80:3001"
      - "2999:2999"
      - "3000:3000"
      - "3001:3001"
      - "3010:3010"
      - "9230:9230"
      - "9231:9231"
      - "9232:9232"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    networks:
      - my_net
    
volumes:
  mongodb:
  redis:
  backend:
  frontend:

networks:
  my_net:
    driver: bridge