version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    expose:
      - 27017
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - my_net

  # Redis service
  redis:
    image: "redis:latest"
    container_name: redis
    restart: unless-stopped
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - my_net

  backend:
    depends_on:
      - mongodb
      - redis
    container_name: "backend"
    restart: unless-stopped
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - 2999
      - 3000
      - 3010
      - 9230
      - 9231
      - 9232
    ports:
      - "2999:2999"
      - "3000:3000"
      - "3010:3010"
      - "9230:9230"
      - "9231:9231"
      - "9232:9232"
    environment:
      - "NODE_ENV=development"
    networks:
      - my_net

  frontend:
    depends_on: 
      - mongodb
      - redis
      - backend
    container_name: "frontend"
    restart: unless-stopped
    build:
      context: ./react_main
      dockerfile: dockerfile
    expose:
      - 80
    ports:
      - "80:80"
    environment:
      - "NODE_ENV=development"
    stdin_open: true
    networks:
      - my_net

volumes:
  local-mongo:

networks:
  my_net:
    driver: bridge