FROM mongo:latest

COPY accounts.json /accounts.json
COPY accounts.json /usr/local/bin/accounts.json

ENTRYPOINT [ "tail", "-f", "/dev/null" ]
#CMD ["mongoimport --host 127.0.0.1 --db ultimafia --collection usersfire --type json --file /accounts.json --jsonArray", "mongosh --file mongo-init.js"]